@startuml

class Request
class OkHttpPostClient
enum ServerType
enum DeviceType

Request --- OkHttpPostClient
Request --- ServerType
Request --- DeviceType

class Request {
    {field} - String RequestModel
    {field} - ServerType targetServer
    {method} + post()
    {method} - canSend()
}

class OkHttpPostClient {
    {static} post(json, server)
}

enum ServerType {
    SD_API1
    SD_API4

    {method} getUrl()
    {method} {static} getById(serverId)
}

enum DeviceType {
    PC
    MOBILE
}

class Response {
    {field} response
    {method} + replaceAuctionPrice()
    {method} + getAdm()
}

@enduml